"""Controlled publish error codes."""

from __future__ import annotations


class ControlledPublishError(Exception):
    def __init__(self, code: str, message: str = ""):
        self.code = code
        self.message = message or code
        super().__init__(f"{self.code}: {self.message}")


# Common codes
PUBLISH_DISABLED = "PUBLISH_DISABLED"
NOT_READY_FOR_PUBLISH = "NOT_READY_FOR_PUBLISH"
PRODUCTION_MODE_REQUIRED = "PRODUCTION_MODE_REQUIRED"
CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"
CONFIRMATION_INVALID = "CONFIRMATION_INVALID"
RELEASE_LOCKED = "RELEASE_LOCKED"
CONTENT_ALREADY_EXISTS = "CONTENT_ALREADY_EXISTS"
REVISION_CONFLICT = "REVISION_CONFLICT"
CONTENT_TYPE_MISMATCH = "CONTENT_TYPE_MISMATCH"
MEDIA_NOT_APPROVED = "MEDIA_NOT_APPROVED"
FREEPUBLISH_NOT_APPROVED = "FREEPUBLISH_NOT_APPROVED"
WECHAT_STEP_REQUIRED = "WECHAT_STEP_REQUIRED"
CHANNEL_ALREADY_SUCCEEDED = "CHANNEL_ALREADY_SUCCEEDED"
NETWORK_FORBIDDEN = "NETWORK_FORBIDDEN"
